[package]
name = "rufile"
version = "0.1.0"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.16"
termion = "1.5"
filemagic = "0.12"
chrono = "0.4"
humansize = "1.1.1"
